# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tici Taca Toey Server Build and Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test:
    name: Build, Test & Upload Artifacts
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    outputs:
      branch-name: ${{ steps.extract-branch-name.outputs.branch }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Compile Typescript Code
        run: npm run build
      - name: Run Tests
        run: npm test
      - name: Extract branch name
        id: extract-branch-name
        run: |
          BRANCH_REF=${{ github.ref }}
          BRANCH_NAME=${BRANCH_REF#refs/heads/}
          echo "::set-output name=branch::$BRANCH_NAME"
      - name: Create artifact
        run: |
          mkdir artifacts
          cd dist/src
          tar --verbose --create --gzip --file ../../artifacts/tici-taca-toey-servey-${{needs.build-test.outputs.branch-name}}.tar.gz *
          cd ../..
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tici-taca-toey-servey-${{needs.build-test.outputs.branch-name}}
          path: artifacts/tici-taca-toey-servey-${{needs.build-test.outputs.branch-name}}.tar.gz
